### ISSUE TITLE
How do you get sugar?

### ISSUE THREAD

**Issue by dlswimmer** [al132mc/Volcano-Block#1]
I am to the Collis seed and need sugar to make it. I assume I need to get sugarcane to then make sugar. I have harvested hundreds of normies and no drop and also cut down grass with no drop there. I see there is a possible way to get it via crushing stone, but not sure that is the intended path.

**Comment by al132mc** [comment]
Sugarcane is supposed to drop from grass. It's not very common, though.

**Comment by dlswimmer** [comment]
Thanks, I did see that on 4ozscoop's video. I've gone through about a stack and a half of bone meal trying :-) I'll keep at it.
