### ISSUE TITLE
Currently no way to craft a Mysterious Sapling from the Hearth Well mod.

### ISSUE THREAD

**Issue by CaithSidhe** [al132mc/Volcano-Block#100]
So I've been enjoying this pack thus far and recently started automating some of the more tedious jobs using the Grit Vase from the Hearth Well mod but ran into an issue, there's no way to get a mysterious sapling that I've been able to find. Without that sapling there's no way to get the planks you need to make a Tray from Hearth Well which in turn means there is no way to Whitelist/Blacklist a few of the better blocks from Hearth Well. 

I'm assuming it was disabled to make it a little more difficult to make Crystal Blocks, which in the base version of Hearth Well you need the leaves of aforementioned tree to make, but I'm thinking that killing the Tray recipe was an oversight.

Just wanted to put this up here in case that was what happened.

**Comment by al132mc** [comment]
Mysterious sapling is not something that exists in hearth well. None of this has anything to do with me. You grow mysterious trees by right-clicking a regular sapling with mysterious fertilizer.

**Comment by CaithSidhe** [comment]
I tried that method in the pack already and it didn't work, so that doesn't actually solve anything in this case. There's still no way to get Mysterious Wood to make the Mysterious Wood Planks that you need for the tray. There isn't an alternate recipe.

**Comment by CaithSidhe** [comment]
Oh, scratch that, I see what happened. It isn't 100% I just spammed it a ton and it grew. Oversight on my part, didn't notice it was using the fertilizer.
