### ISSUE TITLE
Coop/ infinite fall / blocks not displayed

### ISSUE THREAD

**Issue by BloodyFireXs** [al132mc/Volcano-Block#103]
firstly sorry for my english, so i have a problem with the mods pack when i join a friend i do not see any block but when i run the solo part the world loads and if my friends join me he has the same problem that me before he does not see any block so if someone can help me would be nice thank you

**Comment by BloodyFireXs** [comment]
https://imgur.com/PIUnjJg here a screen

**Comment by al132mc** [comment]
Sorry for the late response. This pack does not work on LAN.
