### ISSUE TITLE
3 blocks not growing crops

### ISSUE THREAD

**Issue by plecoptera** [al132mc/Volcano-Block#104]
![2019-10-08_14 11 01](https://user-images.githubusercontent.com/56318358/66422321-7879cf00-e9d7-11e9-823d-07c19bc38b86.png)

These 3 spots haven't been growing crops no matter how long I hold shift. And I know that holding shift is working, because I can see the cobble plant spitting out stacks of cobble. I tried breaking the crops and the blocks and replacing, but they still aren't growing. I tried closing and saving, reopening-didn't work. I closed the minecraft launcher and reopened the pack but nothing.

**Comment by Dr-Game** [comment]
We've encountered this problem before. Many times. Dozens of times. Please make sure that those crops have enough light to grow, or else they won't grow no matter how long you crop dust them. It may not look like it, but those blocks have a light level that's lower than what's required for natural crop growth.

**Comment by plecoptera** [comment]
Thank you! I feel pretty dumb I didn't even think about light level.
