### ISSUE TITLE
A problem when connecting to a server.

### ISSUE THREAD

**Issue by KingDeadZ** [al132mc/Volcano-Block#110]
![image](https://user-images.githubusercontent.com/38157910/72224453-1652dc00-357b-11ea-9e5f-e7f063543745.png)
My friend and i tried to play in an aternos server, with cracked enabled. Unfortunately, he doesn't have an original mc account. When he tried to join, this error code awaited him, while i could still play on cracked too.

**Comment by al132mc** [comment]
I don't provide tech support for cracked clients

**Comment by KingDeadZ** [comment]
The problem is that he tried to come online with my account ,and  then he got the same error as i sent.
