### ISSUE TITLE
How to mine and break adjacent blocks

### ISSUE THREAD

**Issue by firecrauter** [al132mc/Volcano-Block#118]
I've seen it in this video, and on another channel. How do they do it? 
![automine](https://user-images.githubusercontent.com/7044466/93671388-f44e1980-fa78-11ea-8b6d-91e350b41b88.gif)

**Comment by firecrauter** [comment]
Ah, it's the mod Ore Excavation I suppose, but did they add it, or was it already added in the modpack at the time?

**Comment by Cake12356** [comment]
It's already in the pack, hold the Tilde (Grave/~/`) key to excavate.

**Comment by firecrauter** [comment]
True, I hadn't seen it.
(Settings> Controls> Excavate, choose keybind, and hold down the excavation button while you mine, and the tool appropriate for the task (axe for wood, shovel for dirt, etc.)
