### ISSUE TITLE
Open to LAN issue

### ISSUE THREAD

**Issue by Natanielxxl5000** [al132mc/Volcano-Block#121]
When opening a server to LAN, and having someone join they will spawn without seeing the world, but they will se other players.
I saw someone else putting this on but they did not specify that if you look at JourneyMap, the person joining spawns in the wrong biome. It says "Plains" and "forest" for me but "hell" for my friend.

**Comment by al132mc** [comment]
Known issue that probably won't ever get fixed by the mod dev unfortunately - #38
