### ISSUE TITLE
Quest for melter not working even though I complete mostaly quests plz help

### ISSUE THREAD

**Issue by ng0239083** [al132mc/Volcano-Block#122]
i made calculator also but quest is not going to complete
![Screenshot (14)](https://user-images.githubusercontent.com/80150601/110201619-0cc8b980-7e8a-11eb-8726-0ad827e99336.png)

**Comment by al132mc** [comment]
I'm not sure if I exactly understand, but if you follow the quest trails the calculator quest has 3 requirements and you have only completed 2 of them.

**Comment by ng0239083** [comment]
i made calculator also sir but still quest not completed

**Comment by ng0239083** [comment]
thank u
