### ISSUE TITLE
[Suggestion] JETIF

### ISSUE THREAD

**Issue by Lykrast** [al132mc/Volcano-Block#13]
Since the modpack includes Combustive Fishing, [JETIF](https://minecraft.curseforge.com/projects/jetif) would be a nice addition. It basically adds a proper JEI entry for cooling the fishes in water.

**Comment by al132mc** [comment]
If it was only for that single cooling fish recipe I probably wouldn't add the mod, but because it has Atum integration as well I probably will.

**Comment by al132mc** [comment]
Added in v0.4.4
