### ISSUE TITLE
Can't log in server, apparently NBT too big.

### ISSUE THREAD

**Issue by Vhisarion** [al132mc/Volcano-Block#14]
So, I'm not quite sure how this happened. Epicanna didn't have any trouble logging in a few minutes ago, but when I tried to log in, this error showed up.

[![Screenshot from Gyazo](https://gyazo.com/007454a0ec19b37c149327afe67fa2b8/raw)](https://gyazo.com/007454a0ec19b37c149327afe67fa2b8)

This started while flying around in a broom checking out other people islands. Probably not a chunk loading related, though. What I catch from the error is that there might be something in my inventory that contains an NBT that exceeds 2MB, or I loaded something that does.

Any time I try to log in, it shows 'Loading world' for an instant, then throws that error.

**Comment by Vhisarion** [comment]
Moving my player coordinates worked, but there's something in the zone where the server kicked me out that makes anyone that loads it instantly get kicked out.

![crash zone](https://user-images.githubusercontent.com/44608258/59297405-7fdad700-8c88-11e9-95bb-92a8df2afc90.PNG)

This is the danger zone. It's two islands south of mine (My island is: [x:-448, y:60, z:-461]).

No clue what causes it, sorry for the trouble ;w;

**Comment by al132mc** [comment]
We resolved this earlier today.. though there was a bit of collateral damage to the owner of said island
