### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by umutcantkn** [al132mc/Volcano-Block#19]
Firstly i want to say i have 8gb ram is it unhealt for my rams to run a server? 
Secondly it crashes after nearly 20 second
[crash-2019-06-13_02.21.07-server.txt](https://github.com/al132mc/Volcano-Block/files/3283491/crash-2019-06-13_02.21.07-server.txt)

**Comment by al132mc** [comment]
Let me know if restarting after the crash helps (i.e. has it only happened once?) A similar log was posted today by Hurja [here](https://pastebin.com/9XS3TPAh)

**Comment by umutcantkn** [comment]
yeah its restarted like 4 times there is 4 crash reports in crash folder.

**Comment by al132mc** [comment]
I reported this to the developer, but unfortunately I do not have any easy way for you to fix this. If you knew where on your server there is an advanced powercube and you could figure out how to use MCEdit (or find someone else who does) you could find the block and delete it, but that is not very easy to do, unfortunately.

**Comment by umutcantkn** [comment]
Thanks for help i think i will try to find a guy who knows it

**Comment by al132mc** [comment]
Did you get this resolved?
