### ISSUE TITLE
Compact Storage Issues

### ISSUE THREAD

**Issue by C4L3C4RT3R** [al132mc/Volcano-Block#22]
ComPatched and compact storage mods are not working on servers and I've tested it multiple times. Both mods are on the latest versions and I've tried downgrading the mod to a previous version and it still doesn't work. If you could take the time to look into the issue it would be a big help. 

Love the pack by the way!

**Comment by al132mc** [comment]
In what way are they not working? They work fine on our server to the best of my knowledge..

**Comment by C4L3C4RT3R** [comment]
Let me explain in better detail. I'll place the **Chest Builder** down and open it to create my custom chest. After I've set my chest size, it does not list the amount of materials I need to create said chest. For example: If I were to create a 11x11 chest it does not show the amount of materials I need to create the chest. 

It could be something I'm overlooking but it doesn't appear to work. 

![2019-06-12_23 34 38](https://user-images.githubusercontent.com/35306753/59404061-c56fd080-8d6a-11e9-9c18-170e2984ae46.png)

**Comment by al132mc** [comment]
Can you confirm for me that this is different in single player?

**Comment by C4L3C4RT3R** [comment]
I will have a look.

**Comment by C4L3C4RT3R** [comment]
Yes, same issue in single player.

**Comment by al132mc** [comment]
Does this not show for you if you hover over the ingredients like this? ![screenshot](https://user-images.githubusercontent.com/39097092/59404403-01576580-8d6c-11e9-8885-617ae9b749ce.png)

**Comment by C4L3C4RT3R** [comment]
I just re-downloaded the client and updated the server and everything seems to be working now, I wasn't getting the **Amount required** before but I am now. Thanks!

**Comment by al132mc** [comment]
alright, weird. Anyway, i'm glad to hear that everything seems to be working now!
