### ISSUE TITLE
Diamonds in crafting grid

### ISSUE THREAD

**Issue by MyCraftablRomnce** [al132mc/Volcano-Block#27]
I have noticed this for a little bit and thought it was on my side i messed with them and got the stack to 32 diamonds but when i got back on today it is back to 64 diamonds. 
![image](https://user-images.githubusercontent.com/27517393/59547161-f2e58700-8eee-11e9-8810-0faa9953ce4f.png)

**Comment by al132mc** [comment]
https://github.com/Tfarcenim/crafting-station/issues/2

**Comment by al132mc** [comment]
Doesn't happen on vanilla crafting tables by the way, to anyone who happens this issue

**Comment by enderger** [comment]
This is an issue found in many modpacks. It's origin is unknown, and is not always limited to modded crafters.

**Comment by enderger** [comment]
I have seen this mostly in lan games

**Comment by al132mc** [comment]
This might(?) actually be fixed now in 1.0.27, we'll see...
