### ISSUE TITLE
Adding more recipes to the Primordialis Reactor

### ISSUE THREAD

**Issue by Vhisarion** [al132mc/Volcano-Block#28]
Automating plants creates a lot of seeds and stuff you won't really need after crafting the next unique crops plant you need. 
Since the primordialis wants a bunch of different stuff, adding more Unique Crops items would be convenient. (Also, doesn't quite make sense that it takes some items like normie or collis seeds, but some doesn't take some legal stuff or ender lily twines).

I've found myself uselessly stacking the following:
- Enderlily Twines
- Ender Lily Seeds
- EULA Seeds
- Legal Stuff
- Pixelsius Shoot

**Comment by al132mc** [comment]
Added all of these in 1.0.4, thank you
