### ISSUE TITLE
Thorium rates too low

### ISSUE THREAD

**Issue by Vhisarion** [al132mc/Volcano-Block#36]
The only way to get thorium for the fusion cores is to dissolve end stone with a 0.54% (or 0.56% I can't remember) rate. You need a total of 18 ingots for the three cores, which make up for 288 Thorium.
That amount of thorium takes around 51k end stone to be dissolved, while there isn't really a good way to automate end stone. 

There's burst seeds, but you need a specific shard to craft them and you'd have to automate getting the mysterious mixture, which I feel is a bit too much since detcord can't be automatically harvested. Could always go for creeper farm, but i feel like 51k is too much. That would fit more as an automation challenge than a main quest.

**Comment by hurja** [comment]
yup need better thorium source

**Comment by al132mc** [comment]
End stone now yields 1 thorium 50% of the time in 1.0.5, closing
