### ISSUE TITLE
Cannot craft diamond pickaxe with the tetra crafting table

### ISSUE THREAD

**Issue by thealpabet** [al132mc/Volcano-Block#37]
I am unable to upgrade a stone pickaxe to a diamond one using the tetra crafting table. i saw it done in chosen architect's lava island episode 2. i am unable to do it.

**Comment by drakkensong21** [comment]
Do you have the right hammer level

**Comment by thealpabet** [comment]
yeah i think i figured it out it needed more integrity. thanks tho
