### ISSUE TITLE
[Aternos] World Generation

### ISSUE THREAD

**Issue by ShadowRocks2** [al132mc/Volcano-Block#41]
So i use atenos to make servers for me and my friends to play on but for some reason when generating a new world it won generate in the nether or just the small island it makes a whole normal world, i know it has something to do with the worldtype but i dont know what to set it too!
Logs if needed:
https://mclo.gs/kctaXKq
![helpme](https://user-images.githubusercontent.com/44444243/59758376-cc5f7d00-925b-11e9-9b4d-4df0a6f3a604.PNG)

**Comment by al132mc** [comment]
You need this bit for Generator: ```{"Topography-Preset":"Lava"}``` Let me know if that works. You can leave the worldtype alone

**Comment by ShadowRocks2** [comment]
thx life saver XD
