### ISSUE TITLE
I died and came on new island

### ISSUE THREAD

**Issue by Orifiael** [al132mc/Volcano-Block#43]
I died (before I set home) and I was in a team, of which I was the owner.
But I created a new island on dead almost 1k meters away.. so I started over there until I could make a water bucket and made an obsidian road (with water bucket) and passed through someone else claim to get home.
- So, created new island on dying
- Waterbucketted an obsidian road through someone else his claim.

**Comment by al132mc** [comment]
I changed something so this shouldn't happen anymore to new users, let me know if you still have problems
