### ISSUE TITLE
Crops growing extremely fast

### ISSUE THREAD

**Issue by kenohio** [al132mc/Volcano-Block#47]
This wasn't happening yesterday, and seems to be new with today's 1.0.8 update.   When I plant a crop it becomes fully grown in about 1 or 2 seconds, with no twerking.  Same with sugar cane.   Trees also grow almost instantly.  My cobblestone plant puts out crazy amounts of cobble.  The hourglasses creates ancient cobble instantly, etc. 

Maybe this is a feature I'm not aware of, but it seems like a glitch with the new version.

**Comment by al132mc** [comment]
Yes, this was a bug in 1.0.7, should be fixed in 1.0.8

**Comment by kenohio** [comment]
Oh okay.  I thought I was on 1.0.8.  I will update again.  Thank you.

**Comment by kenohio** [comment]
Okay, I have the right version now.  Crops and ancient cobble work as expected.  My trees still grow super fast -- from planting the sapling to full grown tree in about 10 to 15 seconds.  Tested 3 times.  It's not a problem though.

**Comment by al132mc** [comment]
could you please type `/gamerule randomTickSpeed` and tell me what # it says

**Comment by kenohio** [comment]
/gamerule randomTickSpeed -- it just says I don't have permission.  Sorry if I'm being daft.

**Comment by al132mc** [comment]
Let's see if anyone else replies

**Comment by kenohio** [comment]
I figured out it is because I was planting the saplings on Fertile Soil.   They grow normally if I plant on regular dirt.  I'm not sure where the Fertile Soil came from -- there was one block of it in the middle of a patch of regular dirt, and it just happened to be where I was planting.

**Comment by al132mc** [comment]
Alright, I will assume this is sorted then
