### ISSUE TITLE
Linux script fails to run

### ISSUE THREAD

**Issue by akielijan** [al132mc/Volcano-Block#48]
Linux script `ServerStart.sh` fails to run. It creates a link with semicolons after the MCVER and FORGE.

The fix is to remove all of the semicolons from `settings.cfg` - it works as a key-value file with newline as a separator, you don't need to use ';' to end the lines.

As you don't have a code on repository, I can't do a pull request to fix the issue.

**Comment by al132mc** [comment]
Should be fixed in future versions going forward
