### ISSUE TITLE
Dupe bug with Atomic Reshaper and Lacusia plant

### ISSUE THREAD

**Issue by betterth** [al132mc/Volcano-Block#50]
While trying to learn lacusia plant and atomic reshaper, I think I discovered a dupe bug. The lacusia plant is taking out the Atomic Reshaper reagant (the stone in this case) but it's not actually removing it from the inventory. So it just copies it over and over. 

Images of setup here: https://imgur.com/a/oT3vEcM

Even with the atomic reshaper unpowered and off, the lacusia plant is duplicating the stone non-stop.

**Comment by al132mc** [comment]
I decided to just disable the lacusia outright in 1.0.11, thank you for letting me know
