### ISSUE TITLE
Breaking Soulus Empty Normal Summoner Dupe

### ISSUE THREAD

**Issue by huberer** [al132mc/Volcano-Block#67]
I have a Tetra Double Diamond Pick Blaze Rod with Efficieny II and Silk Touch I. Whenever I break an empty normal summoner, it dupes it. Every single time. It doesn't go away if I log out or re open Minecraft. It dupes it (e.g.: One block gives 2 blocks when broken and so on).

**Comment by al132mc** [comment]
https://github.com/Yuudaari/soulus/issues/80

**Comment by al132mc** [comment]
Fixed in 1.0.14
