### ISSUE TITLE
Plants do not grow

### ISSUE THREAD

**Issue by BSQChronicles** [al132mc/Volcano-Block#72]
As written by title, after placing the water, for some reasons some blocks do not grow anything except with the bone meal, I find this a big problem.

**Comment by SilverhuntX** [comment]
Have you checked that there is enough lighting?

**Comment by BSQChronicles** [comment]
Of course, can it be because when I place the water underneath there is obsidian?

**Comment by BSQChronicles** [comment]
up?

**Comment by al132mc** [comment]
screenshot please

**Comment by BSQChronicles** [comment]
https://gyazo.com/3835b46f10e01d4ae32d090d53a04fc5

**Comment by al132mc** [comment]
You need more light. I can't help it, that's just how cropdusting works.
