### ISSUE TITLE
Which are the client side mods?

### ISSUE THREAD

**Issue by 9ap** [al132mc/Volcano-Block#73]
I am trying to make my own server and cant figure out which mods need to be taken out, if you can take a screen shot of which mods you have for your server that would be awesome, thanks!

**Comment by al132mc** [comment]
It turns out that actually no mods need to be taken out, but with that being said we provide pre-made server files, which I would highly recommend using. You can find the most recent ones [here](https://www.curseforge.com/minecraft/modpacks/volcano-block/files/2737088)

**Comment by 9ap** [comment]
Thank you so much for the fast response!
