### ISSUE TITLE
Quest Book not recognizing completed quests

### ISSUE THREAD

**Issue by MultipleMean150** [al132mc/Volcano-Block#74]
Currently playing on iskall85's Patreon Volcano Block server.  I've completed 13 quests in Chapter 4 but only 5 have registered as completed & allowed me to claim the rewards.  I remade the items and still not registered.  The 7 items are the Evaporator,  Natron Crystals, Gelatin, Pure Daisy, Mana Pool,  Tanzanite, Amethyst & Pear Saplings. Thoughts on how to have those requested registered as completed?  
![VB Chapter 4 Quests](https://user-images.githubusercontent.com/31947383/60971976-521e9780-a2f3-11e9-9088-67d9406ab167.PNG)

**Comment by al132mc** [comment]
Presumably it's only the evaporator quest that's the problem here, as it won't complete quests no matter what if you don't have the prerequisites. I would try picking up the evaporator and crafting it by itself to clear any NBT data it might have.

**Comment by MultipleMean150** [comment]
Thanks al123mc.  Crafting a new evaporator did the trick but didn't automatically show the others to register as completed & the rewards to appear.  Guess I will have to craft those again.  Thanks for the quick response.
