### ISSUE TITLE
Rotary grinder issue

### ISSUE THREAD

**Issue by NobuUkiyo** [al132mc/Volcano-Block#75]
When putting an item that doe not take long to grind and replacing it with something long (exemple: nugget to blocks) the duration of the grind will be the nugget time even though you are grinding the block.

**Comment by Lykrast** [comment]
Fixed with Prodigy Tech 1.3.1 which just got sent to curseforge.

**Comment by al132mc** [comment]
Updated to this version of prodigy tech in Volcano Block 1.0.16 - should fix this issue
