### ISSUE TITLE
Automating Power Crystals

### ISSUE THREAD

**Issue by Kurtchekov** [al132mc/Volcano-Block#87]
Any chance we could have power crystals from Hearth Well drop themselves once depleted? I can automate recharging and placing them down, but I haven't found a single way to pick them from the world automatically.

It seems that Hearth Well has an option in its config file
```
# Do Power Crystals drop when they become empty? (default: false)
B:powerCrystalDropsWhenEmpty=false
```

Is it possible to change that to true or is that not intended from a game design perspective for this modpack?

**Comment by al132mc** [comment]
It would be nice if power crystals were more automatable, but at the same time I could see players getting confused when their crystals dissapear, especially earlier on when they are not necessarily trying to automate them. I think it's probably best that I leave this alone
