### ISSUE TITLE
TQ claim area is no longer claimed and is registered under [unknown]

### ISSUE THREAD

**Issue by shyshay1** [al132mc/Volcano-Block#89]
When I logged in, after a bit I found out that my machines ticks are very slow, so I tried to reclaim my area, only to find this following message:
"Another user has already claimed in this proximity, A request to override cannot be sent, as the owner isn't online:[unknown]"
and thus my machines can barely function, even dropping a crusher takes forever >.<
Edit: my tick quality is 0% and all my machines ceased to function...

**Comment by shyshay1** [comment]
Hey al, after you fixed it and I logged in today, the bug has returned... the same message of [unknown] has claimed my area...

**Comment by al132mc** [comment]
I updated tiquality yesterday, so hopefully that prevents it from happening again
