### ISSUE TITLE
[BUG] Seed Recipes Don't Work

### ISSUE THREAD

**Issue by cjcj55** [al132mc/Volcano-Block#94]
All of the recipes from Unique Crops do not work.  Is this just me or not?  I am running a server.

**Comment by al132mc** [comment]
If you look carefully those seed recipes you will see that they are in a category called "Seed Crafting" rather than regular vanilla crafting. You craft these seeds in-world with artisia plants. The guide to unique crops talks about this some more.

Keep me updated on your status please.
