### ISSUE TITLE
Craftingstation:tooltables 

### ISSUE THREAD

**Issue by benjami20207** [al132mc/Volcano-Block#95]
This appears when i open my quest book
![Minecraft 1 12 2 8_17_2019 3_32_05 PM](https://user-images.githubusercontent.com/42079722/63217943-3c776b80-c104-11e9-9be0-c80cf43cb7cc.png)
 
![Minecraft 1 12 2 8_17_2019 3_34_39 PM](https://user-images.githubusercontent.com/42079722/63217962-96783100-c104-11e9-8ff6-2816c1593cae.png)

**Comment by al132mc** [comment]
Please update your pack. This was patched a few hours after it was released

**Comment by benjami20207** [comment]
thank you I didn't realize that!
